<#if parameters.allowBlank?if_exists != ""> allowBlank="${parameters.allowBlank?html}"</#if><#rt/>
<#if parameters.blankText?if_exists != ""> blankText="${parameters.blankText?html}"</#if><#rt/>
<#if parameters.emptyText?if_exists != ""> emptyText="${parameters.emptyText?html}"</#if><#rt/>
<#if parameters.grow?if_exists != ""> grow="${parameters.grow?html}"</#if><#rt/>
<#if parameters.growMax?if_exists != ""> growMax="${parameters.growMax?html}"</#if><#rt/>
<#if parameters.growMin?if_exists != ""> growMin="${parameters.growMin?html}"</#if><#rt/>
<#if parameters.mask?if_exists != ""> mask="${parameters.mask?html}"</#if><#rt/>
<#if parameters.maskConfig?if_exists != ""> maskConfig="${parameters.maskConfig?html}"</#if><#rt/>
<#if parameters.maxLength?if_exists != ""> maxLength="${parameters.maxLength?html}"</#if><#rt/>
<#if parameters.minLength?if_exists != ""> minLength="${parameters.minLength?html}"</#if><#rt/>
<#if parameters.minLengthText?if_exists != ""> minLengthText="${parameters.minLengthText?html}"</#if><#rt/>
<#if parameters.regex?if_exists != ""> regex="${parameters.regex?html}"</#if><#rt/>
<#if parameters.regexText?if_exists != ""> regexText="${parameters.regexText?html}"</#if><#rt/>
<#if parameters.selectOnFocus?if_exists != ""> selectOnFocus="${parameters.selectOnFocus?html}"</#if><#rt/>
<#if parameters.validator?if_exists != ""> validator="${parameters.validator?html}"</#if><#rt/>